"""Add_descompte_proveidor_and_marge_guanys

Revision ID: 0bf95df85787
Revises: 10fc5e1f1e4f
Create Date: 2026-09-27 18:06:02.000336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf95df85787'
down_revision: Union[str, Sequence[str], None] = '10fc5e1f1e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('descompte_proveidor', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('articles', sa.Column('marge_guanys', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'marge_guanys')
    op.drop_column('articles', 'descompte_proveidor')
    # ### end Alembic commands ###
