"""Add odometre fields to HistorialAssignacioVehicle and create MantenimentVehicle

Revision ID: 0ce030b318cd
Revises: 2b63f903b9e6
Create Date: 2026-10-01 12:33:36.605411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce030b318cd'
down_revision: Union[str, Sequence[str], None] = '2b63f903b9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manteniments_vehicles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('data_manteniment', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipus', sa.String(length=50), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=False),
    sa.Column('taller', sa.String(length=255), nullable=True),
    sa.Column('cost_euros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('creat_per_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creat_per_id'], ['usuaris.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empreses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('historial_assignacions_vehicles', sa.Column('odometre_inici', sa.Integer(), nullable=True))
    op.add_column('historial_assignacions_vehicles', sa.Column('odometre_fi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historial_assignacions_vehicles', 'odometre_fi')
    op.drop_column('historial_assignacions_vehicles', 'odometre_inici')
    op.drop_table('manteniments_vehicles')
    # ### end Alembic commands ###
