"""Add codi_barres and es_material_continu to articles

Revision ID: 2b63f903b9e6
Revises: 62d313027039
Create Date: 2026-10-01 12:29:37.430304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b63f903b9e6'
down_revision: Union[str, Sequence[str], None] = '62d313027039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('codi_barres', sa.String(length=100), nullable=True))
    op.add_column('articles', sa.Column('es_material_continu', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_unique_constraint(None, 'articles', ['codi_barres'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'es_material_continu')
    op.drop_column('articles', 'codi_barres')
    # ### end Alembic commands ###
