"""Add DocumentFlota i polissa_asseguranca

Revision ID: 33d35fa1f8e2
Revises: 76f3c4bb789c
Create Date: 2026-09-28 18:39:37.276941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d35fa1f8e2'
down_revision: Union[str, Sequence[str], None] = '76f3c4bb789c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_flota',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('tipus_document', sa.String(length=50), nullable=False),
    sa.Column('nom_arxiu', sa.String(length=255), nullable=False),
    sa.Column('ruta_arxiu', sa.String(length=500), nullable=False),
    sa.Column('contingut_extret', sa.Text(), nullable=True),
    sa.Column('data_document', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creat_per_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['creat_per_id'], ['usuaris.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empreses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vehicles', sa.Column('polissa_asseguranca', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'polissa_asseguranca')
    op.drop_table('documents_flota')
    # ### end Alembic commands ###
