"""Add Finca details

Revision ID: 36dea0df66ec
Revises: a001_rls_all
Create Date: 2026-10-01 12:19:16.367037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dea0df66ec'
down_revision: Union[str, Sequence[str], None] = 'a001_rls_all'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finques', sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('finques', sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('finques', sa.Column('ref_cadastral', sa.String(length=50), nullable=True))
    op.add_column('finques', sa.Column('poligon_sigpac', sa.String(length=50), nullable=True))
    op.add_column('finques', sa.Column('parcel_sigpac', sa.String(length=50), nullable=True))
    op.alter_column('tiquets_carburant', 'odometre_foto_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('tiquets_carburant', 'litres',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    op.alter_column('tiquets_carburant', 'import',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('tiquets_carburant', 'odometre_valor',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tiquets_carburant', 'odometre_valor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tiquets_carburant', 'import',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('tiquets_carburant', 'litres',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.alter_column('tiquets_carburant', 'odometre_foto_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('finques', 'parcel_sigpac')
    op.drop_column('finques', 'poligon_sigpac')
    op.drop_column('finques', 'ref_cadastral')
    op.drop_column('finques', 'longitud')
    op.drop_column('finques', 'latitud')
    # ### end Alembic commands ###
