"""Add custom vertical fields

Revision ID: 3d52d9dcceac
Revises: faa14b55e1a5
Create Date: 2026-09-27 19:14:08.043508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d52d9dcceac'
down_revision: Union[str, Sequence[str], None] = 'faa14b55e1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultes_xat_copilot', sa.Column('magatzem_families_default', sa.Text(), nullable=True))
    op.add_column('consultes_xat_copilot', sa.Column('agent_prompt_system', sa.Text(), nullable=True))
    op.alter_column('consultes_xat_copilot', 'vertical',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'SEVALOR'::character varying"))
    op.add_column('empreses', sa.Column('magatzem_families_default', sa.Text(), nullable=True))
    op.add_column('empreses', sa.Column('agent_prompt_system', sa.Text(), nullable=True))
    op.alter_column('empreses', 'vertical',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'SEVALOR'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empreses', 'vertical',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'SEVALOR'::character varying"))
    op.drop_column('empreses', 'agent_prompt_system')
    op.drop_column('empreses', 'magatzem_families_default')
    op.alter_column('consultes_xat_copilot', 'vertical',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'SEVALOR'::character varying"))
    op.drop_column('consultes_xat_copilot', 'agent_prompt_system')
    op.drop_column('consultes_xat_copilot', 'magatzem_families_default')
    # ### end Alembic commands ###
