"""Add estat to AlbaraProveidor

Revision ID: 3d893ddb5a29
Revises: 6db50f394805
Create Date: 2026-10-01 17:40:51.060172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d893ddb5a29'
down_revision: Union[str, Sequence[str], None] = '6db50f394805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albarans_proveidor', sa.Column('estat', sa.String(length=30), server_default='PENDENT_AUDITORIA', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albarans_proveidor', 'estat')
    # ### end Alembic commands ###
