"""Add phase 3 and 4 contract fields

Revision ID: 5278392ca81d
Revises: 9c20249c9f5f
Create Date: 2026-10-02 09:19:03.728759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5278392ca81d'
down_revision: Union[str, Sequence[str], None] = '9c20249c9f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractes_manteniment', sa.Column('renovacio_tacita', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('contractes_manteniment', sa.Column('increment_renovacio_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('contractes_manteniment', sa.Column('motiu_baixa', sa.Text(), nullable=True))
    op.add_column('revisions_contracte', sa.Column('alerta_emesa_dies', sa.Numeric(precision=2, scale=0), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions_contracte', 'alerta_emesa_dies')
    op.drop_column('contractes_manteniment', 'motiu_baixa')
    op.drop_column('contractes_manteniment', 'increment_renovacio_percent')
    op.drop_column('contractes_manteniment', 'renovacio_tacita')
    # ### end Alembic commands ###
