"""Add versio, latitud, longitud to ordres_treball

Revision ID: 62d313027039
Revises: 36dea0df66ec
Create Date: 2026-10-01 12:23:25.842905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d313027039'
down_revision: Union[str, Sequence[str], None] = '36dea0df66ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordres_treball', sa.Column('versio', sa.Integer(), server_default='1', nullable=False))
    op.add_column('ordres_treball', sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('ordres_treball', sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True))
    op.drop_column('ordres_treball', 'version_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordres_treball', sa.Column('version_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_column('ordres_treball', 'longitud')
    op.drop_column('ordres_treball', 'latitud')
    op.drop_column('ordres_treball', 'versio')
    # ### end Alembic commands ###
