"""Add domini_custom to Empresa

Revision ID: 6db50f394805
Revises: 993ec5e1e943
Create Date: 2026-10-01 12:52:18.915931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db50f394805'
down_revision: Union[str, Sequence[str], None] = '993ec5e1e943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empreses', sa.Column('domini_custom', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'empreses', ['domini_custom'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empreses', type_='unique')
    op.drop_column('empreses', 'domini_custom')
    # ### end Alembic commands ###
