"""Add agenda and optimistic locking to OrdreTreball

Revision ID: 71a8a7fab817
Revises: 32048b39e375
Create Date: 2026-09-23 13:18:15.846189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a8a7fab817'
down_revision: Union[str, Sequence[str], None] = '32048b39e375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estocs_magatzem', sa.Column('quantitat_cuarentena', sa.Numeric(precision=12, scale=3), server_default=sa.text('0.0'), nullable=False))
    op.add_column('factures_proveidor', sa.Column('estat', sa.String(length=50), server_default='PENDENT_REVISIO', nullable=False))
    op.add_column('ordres_treball', sa.Column('hora_inici_prevista', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ordres_treball', sa.Column('hora_fi_prevista', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ordres_treball', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordres_treball', 'version_id')
    op.drop_column('ordres_treball', 'hora_fi_prevista')
    op.drop_column('ordres_treball', 'hora_inici_prevista')
    op.drop_column('factures_proveidor', 'estat')
    op.drop_column('estocs_magatzem', 'quantitat_cuarentena')
    # ### end Alembic commands ###
