"""Add agenda and optimistic locking to OrdreTreball

Revision ID: 71a8a7fab817
Revises: 32048b39e375
Create Date: 2026-09-23 13:18:15.846189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a8a7fab817'
down_revision: Union[str, Sequence[str], None] = '32048b39e375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estocs_magatzem', 'quantitat_cuarentena',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('factures_proveidor', 'estat',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'PENDENT'::character varying"))
    op.add_column('ordres_treball', sa.Column('hora_inici_prevista', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ordres_treball', sa.Column('hora_fi_prevista', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ordres_treball', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordres_treball', 'version_id')
    op.drop_column('ordres_treball', 'hora_fi_prevista')
    op.drop_column('ordres_treball', 'hora_inici_prevista')
    op.alter_column('factures_proveidor', 'estat',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'PENDENT'::character varying"))
    op.alter_column('estocs_magatzem', 'quantitat_cuarentena',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###
