"""Spec 006: Taules de Rènting, Consum, Bateria i Tiquets

Revision ID: 76f3c4bb789c
Revises: bf4dd671c630
Create Date: 2026-09-28 17:31:21.481756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f3c4bb789c'
down_revision: Union[str, Sequence[str], None] = 'bf4dd671c630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_assignacions_vehicles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('conductor_id', sa.UUID(), nullable=False),
    sa.Column('data_inici', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motiu', sa.String(length=255), nullable=True),
    sa.Column('creat_per_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuaris.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creat_per_id'], ['usuaris.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empreses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'vehicle_id', 'data_inici', name='uq_assignacio_inici')
    )
    op.create_table('tiquets_combustible',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('conductor_id', sa.UUID(), nullable=False),
    sa.Column('data_tiquet', sa.DateTime(timezone=True), nullable=False),
    sa.Column('import_euros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('litres', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('kwh_recarrega', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('litres_adblue', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('odometre_registrat', sa.Integer(), nullable=False),
    sa.Column('ruta_arxiu_pwa', sa.String(length=500), nullable=True),
    sa.Column('creat_per_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuaris.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creat_per_id'], ['usuaris.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empreses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vehicles', sa.Column('regim_adquisicio', sa.String(length=30), server_default='PROPIETAT', nullable=False))
    op.add_column('vehicles', sa.Column('renting_limit_km', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('tacograf_necessari', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('vehicles', sa.Column('data_propera_descarrega_tacograf', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('capacitat_bateria_kwh', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('vehicles', sa.Column('soh_bateria', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vehicles', sa.Column('places', sa.Integer(), server_default=sa.text('5'), nullable=False))
    op.add_column('vehicles', sa.Column('pes_maxim_autoritzat', sa.Integer(), server_default=sa.text('3500'), nullable=False))
    op.add_column('vehicles', sa.Column('consum_l_100km', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vehicles', sa.Column('consum_mitjana_historica', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vehicles', sa.Column('consum_adblue_litres', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'consum_adblue_litres')
    op.drop_column('vehicles', 'consum_mitjana_historica')
    op.drop_column('vehicles', 'consum_l_100km')
    op.drop_column('vehicles', 'pes_maxim_autoritzat')
    op.drop_column('vehicles', 'places')
    op.drop_column('vehicles', 'soh_bateria')
    op.drop_column('vehicles', 'capacitat_bateria_kwh')
    op.drop_column('vehicles', 'data_propera_descarrega_tacograf')
    op.drop_column('vehicles', 'tacograf_necessari')
    op.drop_column('vehicles', 'renting_limit_km')
    op.drop_column('vehicles', 'regim_adquisicio')
    op.drop_table('tiquets_combustible')
    op.drop_table('historial_assignacions_vehicles')
    # ### end Alembic commands ###
