"""Add finca_id to PlanolBase

Revision ID: 993ec5e1e943
Revises: 0ce030b318cd
Create Date: 2026-10-01 12:47:22.657936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993ec5e1e943'
down_revision: Union[str, Sequence[str], None] = '0ce030b318cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpetes_planols', sa.Column('finca_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'carpetes_planols', 'finques', ['finca_id'], ['id'], ondelete='CASCADE')
    op.add_column('exportacions_pdf_planol', sa.Column('finca_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exportacions_pdf_planol', 'finques', ['finca_id'], ['id'], ondelete='CASCADE')
    op.add_column('planols_base', sa.Column('finca_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'planols_base', 'finques', ['finca_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planols_base', type_='foreignkey')
    op.drop_column('planols_base', 'finca_id')
    op.drop_constraint(None, 'exportacions_pdf_planol', type_='foreignkey')
    op.drop_column('exportacions_pdf_planol', 'finca_id')
    op.drop_constraint(None, 'carpetes_planols', type_='foreignkey')
    op.drop_column('carpetes_planols', 'finca_id')
    # ### end Alembic commands ###
