"""Add Contractes Manteniment

Revision ID: 9c20249c9f5f
Revises: 3d893ddb5a29
Create Date: 2026-10-02 09:18:23.258875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c20249c9f5f'
down_revision: Union[str, Sequence[str], None] = '3d893ddb5a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractes_manteniment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('numero_contracte', sa.String(length=50), nullable=False),
    sa.Column('data_inici', sa.Date(), nullable=False),
    sa.Column('data_fi', sa.Date(), nullable=True),
    sa.Column('import_anual', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('periodicitat', sa.String(length=20), server_default='ANUAL', nullable=False),
    sa.Column('estat', sa.String(length=20), server_default='ACTIU', nullable=False),
    sa.Column('observacions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empreses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero_contracte', name='uq_contractes_empresa_num')
    )
    op.create_table('contractes_manteniment_finques',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('contracte_id', sa.UUID(), nullable=False),
    sa.Column('finca_id', sa.UUID(), nullable=False),
    sa.Column('data_assignacio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contracte_id'], ['contractes_manteniment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empreses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['finques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contracte_id', 'finca_id', name='uq_contracte_finca')
    )
    op.create_table('revisions_contracte',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('contracte_id', sa.UUID(), nullable=False),
    sa.Column('ordre_treball_id', sa.UUID(), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('estat', sa.String(length=20), server_default='PENDENT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contracte_id'], ['contractes_manteniment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empreses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ordre_treball_id'], ['ordres_treball.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Activar RLS i crear polítiques
    for taula in ['contractes_manteniment', 'contractes_manteniment_finques', 'revisions_contracte']:
        op.execute(f"ALTER TABLE {taula} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"CREATE POLICY tenant_isolation_policy ON {taula} USING (empresa_id = current_setting('app.current_empresa_id', true)::uuid);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for taula in ['revisions_contracte', 'contractes_manteniment_finques', 'contractes_manteniment']:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {taula};")
        
    op.drop_table('revisions_contracte')
    op.drop_table('contractes_manteniment_finques')
    op.drop_table('contractes_manteniment')
    # ### end Alembic commands ###
