"""Remove extra columns from copilot

Revision ID: add1f9f7ff7a
Revises: 3d52d9dcceac
Create Date: 2026-09-27 19:14:22.406920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add1f9f7ff7a'
down_revision: Union[str, Sequence[str], None] = '3d52d9dcceac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultes_xat_copilot', 'agent_prompt_system')
    op.drop_column('consultes_xat_copilot', 'magatzem_families_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultes_xat_copilot', sa.Column('magatzem_families_default', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('consultes_xat_copilot', sa.Column('agent_prompt_system', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
