"""baseline esquema actual

Revision ID: db371c77b254
Revises: 
Create Date: 2026-09-11 16:31:22.833836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db371c77b254'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_substitucions_empresa'), table_name='estancies_substitucio')  # noqa -- baseline: no aplicar
    # op.drop_table('estancies_substitucio')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_alertes_copilot_empresa'), table_name='alertes_garantia_recompra')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_alertes_copilot_estat'), table_name='alertes_garantia_recompra')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_alertes_copilot_tipus'), table_name='alertes_garantia_recompra')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_articles_empresa'), table_name='articles')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_articles_parent'), table_name='articles')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_audit_jornada_empresa'), table_name='auditoria_registres_jornada')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_audit_jornada_shift'), table_name='auditoria_registres_jornada')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_auditories_empresa'), table_name='auditories_post_obra')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_auditories_estat'), table_name='auditories_post_obra')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_auditories_ordre'), table_name='auditories_post_obra')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_capes_empresa'), table_name='capes_anotacions')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_capes_ordre'), table_name='capes_anotacions')  # noqa -- baseline: no aplicar
    # op.alter_column('capes_vectorials', 'color_hex',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'#2563eb'::character varying"))
    # op.alter_column('capes_vectorials', 'gruix_linia',  # noqa -- baseline: no aplicar
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    # op.alter_column('capes_vectorials', 'opacitat_percent',  # noqa -- baseline: no aplicar
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    # op.alter_column('capes_vectorials', 'visible',  # noqa -- baseline: no aplicar
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # op.drop_index(op.f('idx_capes_vectorials_empresa'), table_name='capes_vectorials')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_capes_vectorials_ordre'), table_name='capes_vectorials')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_capes_vectorials_planol'), table_name='capes_vectorials')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_carpetes_categoria'), table_name='carpetes_planols')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_carpetes_client'), table_name='carpetes_planols')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_carpetes_empresa'), table_name='carpetes_planols')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_clients_empresa'), table_name='clients')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_clients_nif'), table_name='clients')  # noqa -- baseline: no aplicar
    # op.add_column('consultes_xat_copilot', sa.Column('node_ia_actiu', sa.Boolean(), nullable=False))  # noqa -- baseline: no aplicar
    # op.add_column('consultes_xat_copilot', sa.Column('node_ia_url', sa.String(length=255), nullable=True))  # noqa -- baseline: no aplicar
    # op.add_column('consultes_xat_copilot', sa.Column('feature_copilot_ia', sa.Boolean(), nullable=False))  # noqa -- baseline: no aplicar
    # op.add_column('consultes_xat_copilot', sa.Column('feature_flota', sa.Boolean(), nullable=False))  # noqa -- baseline: no aplicar
    # op.add_column('consultes_xat_copilot', sa.Column('feature_planols', sa.Boolean(), nullable=False))  # noqa -- baseline: no aplicar
    # op.add_column('consultes_xat_copilot', sa.Column('feature_telegram', sa.Boolean(), nullable=False))  # noqa -- baseline: no aplicar
    # op.add_column('consultes_xat_copilot', sa.Column('data_onboarding', sa.DateTime(timezone=True), nullable=False))  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_xat_copilot_created'), table_name='consultes_xat_copilot')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_xat_copilot_empresa'), table_name='consultes_xat_copilot')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_xat_copilot_usuari'), table_name='consultes_xat_copilot')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_converses_client'), table_name='converses_notificacio')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_converses_empresa'), table_name='converses_notificacio')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_converses_estat'), table_name='converses_notificacio')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_converses_ordre'), table_name='converses_notificacio')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_cae_caducitat'), table_name='documents_cae_rc')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_cae_empresa'), table_name='documents_cae_rc')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_cae_proveidor'), table_name='documents_cae_rc')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_eines_empresa'), table_name='eines_custodia')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_eines_operari'), table_name='eines_custodia')  # noqa -- baseline: no aplicar
    # op.alter_column('empreses', 'estat_pagament',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'TRIAL'::character varying"))
    # op.drop_index(op.f('idx_estocs_article'), table_name='estocs_magatzem')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_estocs_empresa'), table_name='estocs_magatzem')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_estocs_magatzem'), table_name='estocs_magatzem')  # noqa -- baseline: no aplicar
    # op.alter_column('exportacions_pdf_planol', 'escala_grafica',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'1:500'::character varying"))
    # op.alter_column('exportacions_pdf_planol', 'estat',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'GENERAT'::character varying"))
    # op.drop_index(op.f('idx_exportacions_empresa'), table_name='exportacions_pdf_planol')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_factures_client'), table_name='factures_capcalera')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_factures_empresa'), table_name='factures_capcalera')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_factures_serie_num'), table_name='factures_capcalera')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_factures_linies_empresa'), table_name='factures_linies')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_factures_linies_factura'), table_name='factures_linies')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_fact_prov_empresa'), table_name='factures_proveidor')  # noqa -- baseline: no aplicar
    # op.alter_column('faqs_corporatives_rag', 'categoria',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'GENERAL'::character varying"))
    # op.drop_index(op.f('idx_faqs_empresa'), table_name='faqs_corporatives_rag')  # noqa -- baseline: no aplicar
    # op.alter_column('finques', 'dades_sigpac',  # noqa -- baseline: no aplicar
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # op.drop_index(op.f('idx_finques_client'), table_name='finques')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_finques_coords_gps'), table_name='finques', postgresql_using='gist')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_finques_empresa'), table_name='finques')  # noqa -- baseline: no aplicar
    # op.drop_column('finques', 'coords_gps')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_picking_empresa'), table_name='fulles_picking')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_picking_ordre'), table_name='fulles_picking')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_incidencies_coords'), table_name='incidencies', postgresql_using='gist')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_incidencies_empresa'), table_name='incidencies')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_incidencies_estat'), table_name='incidencies')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_incidencies_ordre'), table_name='incidencies')  # noqa -- baseline: no aplicar
    # op.drop_column('incidencies', 'coords_gps')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_linies_picking_empresa'), table_name='linies_picking')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_linies_picking_parent'), table_name='linies_picking')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_magatzems_empresa'), table_name='magatzems')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_memo_empresa'), table_name='memorandums_tecnics_copilot')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_memo_estat'), table_name='memorandums_tecnics_copilot')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_memo_incidencia'), table_name='memorandums_tecnics_copilot')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_memo_ot'), table_name='memorandums_tecnics_copilot')  # noqa -- baseline: no aplicar
    # op.alter_column('missatges_notificacio', 'tipus_esdeveniment',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'MISSATGE_TEXT'::character varying"))
    # op.alter_column('missatges_notificacio', 'estat_aprobacio',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'PENDENT'::character varying"))
    # op.drop_index(op.f('idx_missatges_conversa'), table_name='missatges_notificacio')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_missatges_empresa'), table_name='missatges_notificacio')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_missatges_token_aprobacio'), table_name='missatges_notificacio')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_missatges_token_factura'), table_name='missatges_notificacio')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_ordres_client'), table_name='ordres_treball')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_ordres_data'), table_name='ordres_treball')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_ordres_empresa'), table_name='ordres_treball')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_ordres_estat'), table_name='ordres_treball')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_outbox_empresa'), table_name='outbox_enviaments_aeat')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_outbox_estat'), table_name='outbox_enviaments_aeat')  # noqa -- baseline: no aplicar
    # op.alter_column('pins_incidencia_planol', 'simbol',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'AVARIA_REG'::character varying"))
    # op.alter_column('pins_incidencia_planol', 'estat',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDENT_REVISIO'::character varying"))
    # op.drop_index(op.f('idx_pins_capa'), table_name='pins_incidencia_planol')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_pins_empresa'), table_name='pins_incidencia_planol')  # noqa -- baseline: no aplicar
    # op.alter_column('planols_base', 'carpeta_id',  # noqa -- baseline: no aplicar
               existing_type=sa.UUID(),
               nullable=False)
    # op.alter_column('planols_base', 'projeccio_origen',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'WGS84'::character varying"))
    # op.drop_index(op.f('idx_planols_carpeta'), table_name='planols_base')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_planols_client'), table_name='planols_base')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_planols_empresa'), table_name='planols_base')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_proveidors_empresa'), table_name='proveidors')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_proveidors_nif'), table_name='proveidors')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_sif_data'), table_name='registre_esdeveniments_sif')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_sif_empresa'), table_name='registre_esdeveniments_sif')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_sif_esdeveniment'), table_name='registre_esdeveniments_sif')  # noqa -- baseline: no aplicar
    # op.alter_column('registres_jornada_laboral', 'hores_ordinaries',  # noqa -- baseline: no aplicar
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    # op.alter_column('registres_jornada_laboral', 'hores_extraordinaries',  # noqa -- baseline: no aplicar
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    # op.drop_index(op.f('idx_jornada_data'), table_name='registres_jornada_laboral')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_jornada_empresa'), table_name='registres_jornada_laboral')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_jornada_estat'), table_name='registres_jornada_laboral')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_jornada_usuari'), table_name='registres_jornada_laboral')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_slots_empresa'), table_name='slots_jornada')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_tiquets_empresa'), table_name='tiquets_carburant')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_tiquets_vehicle'), table_name='tiquets_carburant')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_tokens_invitacio_client'), table_name='tokens_invitacio_telegram')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_tokens_invitacio_empresa'), table_name='tokens_invitacio_telegram')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_tokens_invitacio_token'), table_name='tokens_invitacio_telegram')  # noqa -- baseline: no aplicar
    # op.alter_column('usuaris', 'estat_operatiu',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'DISPONIBLE'::character varying"))
    # op.alter_column('usuaris', 'cost_hora_eur',  # noqa -- baseline: no aplicar
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False,
               existing_server_default=sa.text('22.50'))
    # op.alter_column('usuaris', 'carnet_conduir',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'B'::character varying"))
    # op.alter_column('usuaris', 'intents_pin_fallits',  # noqa -- baseline: no aplicar
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # op.alter_column('usuaris', 'pin_bloquejat',  # noqa -- baseline: no aplicar
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # op.drop_index(op.f('idx_usuaris_cap_de_grup'), table_name='usuaris')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_usuaris_email'), table_name='usuaris', postgresql_where='(email IS NOT NULL)')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_usuaris_empresa'), table_name='usuaris')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_usuaris_especialitat'), table_name='usuaris')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_usuaris_estat_operatiu'), table_name='usuaris')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_usuaris_rol'), table_name='usuaris')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_usuaris_telefon'), table_name='usuaris', postgresql_where='(telefon IS NOT NULL)')  # noqa -- baseline: no aplicar
    # op.drop_index(op.f('idx_vehicles_empresa'), table_name='vehicles')  # noqa -- baseline: no aplicar
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('idx_vehicles_empresa'), 'vehicles', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_usuaris_telefon'), 'usuaris', ['telefon'], unique=False, postgresql_where='(telefon IS NOT NULL)')  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_usuaris_rol'), 'usuaris', ['rol'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_usuaris_estat_operatiu'), 'usuaris', ['estat_operatiu'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_usuaris_especialitat'), 'usuaris', ['especialitat'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_usuaris_empresa'), 'usuaris', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_usuaris_email'), 'usuaris', ['email'], unique=False, postgresql_where='(email IS NOT NULL)')  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_usuaris_cap_de_grup'), 'usuaris', ['cap_de_grup_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('usuaris', 'pin_bloquejat',  # noqa -- baseline: no aplicar
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # op.alter_column('usuaris', 'intents_pin_fallits',  # noqa -- baseline: no aplicar
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # op.alter_column('usuaris', 'carnet_conduir',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'B'::character varying"))
    # op.alter_column('usuaris', 'cost_hora_eur',  # noqa -- baseline: no aplicar
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True,
               existing_server_default=sa.text('22.50'))
    # op.alter_column('usuaris', 'estat_operatiu',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'DISPONIBLE'::character varying"))
    # op.create_index(op.f('idx_tokens_invitacio_token'), 'tokens_invitacio_telegram', ['token_hash'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_tokens_invitacio_empresa'), 'tokens_invitacio_telegram', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_tokens_invitacio_client'), 'tokens_invitacio_telegram', ['client_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_tiquets_vehicle'), 'tiquets_carburant', ['vehicle_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_tiquets_empresa'), 'tiquets_carburant', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_slots_empresa'), 'slots_jornada', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_jornada_usuari'), 'registres_jornada_laboral', ['usuari_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_jornada_estat'), 'registres_jornada_laboral', ['estat'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_jornada_empresa'), 'registres_jornada_laboral', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_jornada_data'), 'registres_jornada_laboral', ['data_jornada'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('registres_jornada_laboral', 'hores_extraordinaries',  # noqa -- baseline: no aplicar
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    # op.alter_column('registres_jornada_laboral', 'hores_ordinaries',  # noqa -- baseline: no aplicar
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    # op.create_index(op.f('idx_sif_esdeveniment'), 'registre_esdeveniments_sif', ['codi_esdeveniment'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_sif_empresa'), 'registre_esdeveniments_sif', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_sif_data'), 'registre_esdeveniments_sif', ['data_creacio'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_proveidors_nif'), 'proveidors', ['nif'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_proveidors_empresa'), 'proveidors', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_planols_empresa'), 'planols_base', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_planols_client'), 'planols_base', ['client_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_planols_carpeta'), 'planols_base', ['carpeta_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('planols_base', 'projeccio_origen',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'WGS84'::character varying"))
    # op.alter_column('planols_base', 'carpeta_id',  # noqa -- baseline: no aplicar
               existing_type=sa.UUID(),
               nullable=True)
    # op.create_index(op.f('idx_pins_empresa'), 'pins_incidencia_planol', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_pins_capa'), 'pins_incidencia_planol', ['capa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('pins_incidencia_planol', 'estat',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PENDENT_REVISIO'::character varying"))
    # op.alter_column('pins_incidencia_planol', 'simbol',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'AVARIA_REG'::character varying"))
    # op.create_index(op.f('idx_outbox_estat'), 'outbox_enviaments_aeat', ['estat_enviament'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_outbox_empresa'), 'outbox_enviaments_aeat', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_ordres_estat'), 'ordres_treball', ['estat'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_ordres_empresa'), 'ordres_treball', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_ordres_data'), 'ordres_treball', ['data_planificacio'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_ordres_client'), 'ordres_treball', ['client_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_missatges_token_factura'), 'missatges_notificacio', ['token_descarrega_factura'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_missatges_token_aprobacio'), 'missatges_notificacio', ['token_aprobacio'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_missatges_empresa'), 'missatges_notificacio', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_missatges_conversa'), 'missatges_notificacio', ['conversa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('missatges_notificacio', 'estat_aprobacio',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'PENDENT'::character varying"))
    # op.alter_column('missatges_notificacio', 'tipus_esdeveniment',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'MISSATGE_TEXT'::character varying"))
    # op.create_index(op.f('idx_memo_ot'), 'memorandums_tecnics_copilot', ['ordre_treball_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_memo_incidencia'), 'memorandums_tecnics_copilot', ['incidencia_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_memo_estat'), 'memorandums_tecnics_copilot', ['estat'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_memo_empresa'), 'memorandums_tecnics_copilot', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_magatzems_empresa'), 'magatzems', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_linies_picking_parent'), 'linies_picking', ['picking_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_linies_picking_empresa'), 'linies_picking', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.add_column('incidencies', sa.Column('coords_gps', sa.NullType(), autoincrement=False, nullable=True))  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_incidencies_ordre'), 'incidencies', ['ordre_treball_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_incidencies_estat'), 'incidencies', ['estat'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_incidencies_empresa'), 'incidencies', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_incidencies_coords'), 'incidencies', ['coords_gps'], unique=False, postgresql_using='gist')  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_picking_ordre'), 'fulles_picking', ['ordre_treball_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_picking_empresa'), 'fulles_picking', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.add_column('finques', sa.Column('coords_gps', sa.NullType(), autoincrement=False, nullable=False))  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_finques_empresa'), 'finques', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_finques_coords_gps'), 'finques', ['coords_gps'], unique=False, postgresql_using='gist')  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_finques_client'), 'finques', ['client_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('finques', 'dades_sigpac',  # noqa -- baseline: no aplicar
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # op.create_index(op.f('idx_faqs_empresa'), 'faqs_corporatives_rag', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('faqs_corporatives_rag', 'categoria',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'GENERAL'::character varying"))
    # op.create_index(op.f('idx_fact_prov_empresa'), 'factures_proveidor', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_factures_linies_factura'), 'factures_linies', ['factura_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_factures_linies_empresa'), 'factures_linies', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_factures_serie_num'), 'factures_capcalera', ['serie', 'numero_factura'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_factures_empresa'), 'factures_capcalera', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_factures_client'), 'factures_capcalera', ['client_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_exportacions_empresa'), 'exportacions_pdf_planol', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('exportacions_pdf_planol', 'estat',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'GENERAT'::character varying"))
    # op.alter_column('exportacions_pdf_planol', 'escala_grafica',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'1:500'::character varying"))
    # op.create_index(op.f('idx_estocs_magatzem'), 'estocs_magatzem', ['magatzem_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_estocs_empresa'), 'estocs_magatzem', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_estocs_article'), 'estocs_magatzem', ['article_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('empreses', 'estat_pagament',  # noqa -- baseline: no aplicar
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'TRIAL'::character varying"))
    # op.create_index(op.f('idx_eines_operari'), 'eines_custodia', ['custodiat_per_operari_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_eines_empresa'), 'eines_custodia', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_cae_proveidor'), 'documents_cae_rc', ['proveidor_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_cae_empresa'), 'documents_cae_rc', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_cae_caducitat'), 'documents_cae_rc', ['data_caducitat'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_converses_ordre'), 'converses_notificacio', ['ordre_treball_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_converses_estat'), 'converses_notificacio', ['estat'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_converses_empresa'), 'converses_notificacio', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_converses_client'), 'converses_notificacio', ['client_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_xat_copilot_usuari'), 'consultes_xat_copilot', ['usuari_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_xat_copilot_empresa'), 'consultes_xat_copilot', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_xat_copilot_created'), 'consultes_xat_copilot', ['created_at'], unique=False)  # noqa -- baseline: no aplicar
    # op.drop_column('consultes_xat_copilot', 'data_onboarding')  # noqa -- baseline: no aplicar
    # op.drop_column('consultes_xat_copilot', 'feature_telegram')  # noqa -- baseline: no aplicar
    # op.drop_column('consultes_xat_copilot', 'feature_planols')  # noqa -- baseline: no aplicar
    # op.drop_column('consultes_xat_copilot', 'feature_flota')  # noqa -- baseline: no aplicar
    # op.drop_column('consultes_xat_copilot', 'feature_copilot_ia')  # noqa -- baseline: no aplicar
    # op.drop_column('consultes_xat_copilot', 'node_ia_url')  # noqa -- baseline: no aplicar
    # op.drop_column('consultes_xat_copilot', 'node_ia_actiu')  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_clients_nif'), 'clients', ['nif'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_clients_empresa'), 'clients', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_carpetes_empresa'), 'carpetes_planols', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_carpetes_client'), 'carpetes_planols', ['client_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_carpetes_categoria'), 'carpetes_planols', ['categoria'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_capes_vectorials_planol'), 'capes_vectorials', ['planol_base_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_capes_vectorials_ordre'), 'capes_vectorials', ['ordre_treball_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_capes_vectorials_empresa'), 'capes_vectorials', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.alter_column('capes_vectorials', 'visible',  # noqa -- baseline: no aplicar
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # op.alter_column('capes_vectorials', 'opacitat_percent',  # noqa -- baseline: no aplicar
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    # op.alter_column('capes_vectorials', 'gruix_linia',  # noqa -- baseline: no aplicar
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    # op.alter_column('capes_vectorials', 'color_hex',  # noqa -- baseline: no aplicar
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'#2563eb'::character varying"))
    # op.create_index(op.f('idx_capes_ordre'), 'capes_anotacions', ['ordre_treball_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_capes_empresa'), 'capes_anotacions', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_auditories_ordre'), 'auditories_post_obra', ['ordre_treball_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_auditories_estat'), 'auditories_post_obra', ['estat'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_auditories_empresa'), 'auditories_post_obra', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_audit_jornada_shift'), 'auditoria_registres_jornada', ['shift_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_audit_jornada_empresa'), 'auditoria_registres_jornada', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_articles_parent'), 'articles', ['parent_material_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_articles_empresa'), 'articles', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_alertes_copilot_tipus'), 'alertes_garantia_recompra', ['tipus_alerta'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_alertes_copilot_estat'), 'alertes_garantia_recompra', ['estat'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_index(op.f('idx_alertes_copilot_empresa'), 'alertes_garantia_recompra', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_table('estancies_substitucio',  # noqa -- baseline: no aplicar
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('empresa_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_principal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_substitucio_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_inici', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('data_fi', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('motiu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empreses.id'], name=op.f('estancies_substitucio_empresa_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_principal_id'], ['vehicles.id'], name=op.f('estancies_substitucio_vehicle_principal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_substitucio_id'], ['vehicles.id'], name=op.f('estancies_substitucio_vehicle_substitucio_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('estancies_substitucio_pkey'))
    )
    # op.create_index(op.f('idx_substitucions_empresa'), 'estancies_substitucio', ['empresa_id'], unique=False)  # noqa -- baseline: no aplicar
    # op.create_table('spatial_ref_sys',  # noqa -- baseline: no aplicar
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
