"""Add carnet, asseguranca, itv state and reparacions to Vehicle

Revision ID: bf4dd671c630
Revises: add1f9f7ff7a
Create Date: 2026-09-28 17:21:55.797056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4dd671c630'
down_revision: Union[str, Sequence[str], None] = 'add1f9f7ff7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('estat_itv', sa.String(length=50), server_default='FAVORABLE', nullable=False))
    op.add_column('vehicles', sa.Column('data_caducitat_asseguranca', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('companyia_asseguradora', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('carnet_necessari', sa.String(length=10), server_default='B', nullable=False))
    op.add_column('vehicles', sa.Column('historial_reparacions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'historial_reparacions')
    op.drop_column('vehicles', 'carnet_necessari')
    op.drop_column('vehicles', 'companyia_asseguradora')
    op.drop_column('vehicles', 'data_caducitat_asseguranca')
    op.drop_column('vehicles', 'estat_itv')
    # ### end Alembic commands ###
