"""Add_garantia_observacions_incidencies_to_eina

Revision ID: faa14b55e1a5
Revises: 0bf95df85787
Create Date: 2026-09-27 18:22:54.540343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa14b55e1a5'
down_revision: Union[str, Sequence[str], None] = '0bf95df85787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eines_custodia', sa.Column('data_fi_garantia', sa.Date(), nullable=True))
    op.add_column('eines_custodia', sa.Column('observacions', sa.Text(), nullable=True))
    op.add_column('eines_custodia', sa.Column('incidencies', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eines_custodia', 'incidencies')
    op.drop_column('eines_custodia', 'observacions')
    op.drop_column('eines_custodia', 'data_fi_garantia')
    # ### end Alembic commands ###
